### ISSUE TITLE
Add Analytic tracking for events

### ISSUE THREAD

**Issue by RongxinZhang** [Retsly/log#41]
#### events to track
---
**Developers:**
- [ ] first api call
- [ ] no api calls for a 1 week (how can we track this?)
- [ ] first application created
- [ ] application submitted for review
- [ ] application denied for access
- [ ] revocation of access 
- [ ] acceptance of access  

**MLS:**
- [ ] first application approval / rejection
- [ ] reviewing new app

**Agents:**
- [ ] Approving app to use data

_Add additional events_

Reference: https://github.com/Retsly/log/issues/39
